# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: MyKewlPool

steps:
- task: PowerShell@2
  pwsh: true
  inputs:
    filePath: 'dbcc.ps1'
  env:
    KEY: $(key)
    CLEANUP: true
